services:
  db:
    container_name: "bot-db"
    image: postgres:16.2
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: "$DB_PASS"
      POSTGRES_USER: "$DB_USER"
      POSTGRES_DB: "$DB_NAME"
      POSTGRES_PORT: "$DB_PORT"
    # dev-mode only
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate_and_tests:
    container_name: "bot-setup"
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    command: ["make", "test", "db_setup"]

  api:
    container_name: "bot-api"
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    depends_on:
      - migrate_and_tests
    env_file:
       - .env
  # dev-mode only
    volumes:
       - "./:/app"
    ports:
       - "127.0.0.1:8000:8000"
    command: ["fastapi", "dev", "api/main.py", "--port", "8000", "--host", "0.0.0.0"]

volumes:
  postgres_data: